---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-assignment
---
apiVersion: v1
data:
  MYSQL_DATABASE: tododb
  MYSQL_HOST: tododb-service.lab-assignment.svc.cluster.local
  MYSQL_PASSWORD: P@ssword
  MYSQL_USER: root
kind: ConfigMap
metadata:
  name: dbconfig
  namespace: lab-assignment
---
apiVersion: v1
kind: Service
metadata:
  name: tododb-service
  namespace: lab-assignment
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: lab-assignment
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/mysqldata
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: lab-assignment
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-loadbalancer
  namespace: lab-assignment
spec:
  ports:
  - port: 8090
  selector:
    app: todoapi-app
  type: LoadBalancer