apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: lab-assignment
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow