apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: lab-assignment
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/mysqldata
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow